### ISSUE TITLE
Bład konfiguracji sieci - bonding przy pierwszym uruchomieniu maszyny

### ISSUE THREAD

**Issue by bockpl** [bockpl/ubuntu18.04src#1]
Przy poniższej konfiguracji sieci /etc/network/interfaces

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet manual
bond-master bond0

auto eth1
iface eth1 inet manual
pre-up sleep 4
bond-master bond0

auto bond0
iface bond0 inet dhcp
bond-mode active-backup
bond-miimon 100
bond-downdelay 200
bond-updelay 200
bond-primary eth0
slaves eth0 eth1

auto bond0.197
iface bond0.197 inet dhcp
vlan_raw_device bond0

Podczas pierwszego startu maszyny z sieci, gdy formatują się dyski, zgrywa obraz i następnie staruje system z lokalnego dysku

Konfiguracja sieci jest nieprawidłowa. Interfejs bond0.197 nie jest podniesiony i jest widoczny interfejs renameX po wydaniu polecenia ifconfig -a

Po kolejnym restarcie sieć działa prawidłowo.

**Comment by bockpl** [comment]
Czy to nadal aktualne? Od jakiegoś czasu system po starcie z sieci i zgraniu obrazu na dysk automatycznie się restartuje.

**Comment by kedarnok** [comment]
Do zamknięcia. SIeć obsługiwna jest przez netplan. Bonding działa.
