### ISSUE TITLE
Brak pliku fstab

### ISSUE THREAD

**Issue by kedarnok** [bockpl/ubuntu18.04src#2]
Plik fstab nie jest wgrywany z obrazu/initrd.conf - ogólnie testowałem wszystkie możliwe lokalizacje i nie działa.
Workaround:
Admin musi wgrać własny plik fstab do katalogu CONFIGS/HOSTNAME/etc/ na MFS-ie
Plik dostępny w repozytorium w katalogu etc/

**Comment by bockpl** [comment]
Plik fstab powinien być właśnie w konfiguracji stworzonej przez administratora czyli CONFIGS/[hostname]/etc/fstab.
Czy nadal są problemy z fstab?

**Comment by kedarnok** [comment]
Do zamknięcia
