### ISSUE TITLE
Błędnie działajaca synchronizacja czasu

### ISSUE THREAD

**Issue by przemyslawtrzeciak** [bockpl/ubuntu18.04src#3]
W komunikacie logów znajduje się wpis:
mfsmaster[1944]: got change log from the future (1s) - please synchronize clocks

Proszę o wskazanie ścieżki do synchronizacji czasu, tymczasowo zmieniłem serwer synchronizacji na nasz w usłudze systemd-timesyncd...

**Comment by bockpl** [comment]
Usługa mfsmaster nie jest częścią tego projektu.
Co znaczy ścieżki do synchronizacji czasu? Pokaż co ustawiłeś, a co nie było ustawione.

**Comment by przemyslawtrzeciak** [comment]
Pewnie żartujesz, ale to skomentuje. Oczywiście mfsmaster jest tylko procesem który działa w oparciu o szablon ubuntu 18.04 o którym doskonale wiesz. Ww proces mfsmaster informuje o błędach w czasie między sobą a drugim również wyprodukowanym z tego obrazu nodem (relacja między mfs1 i mfs2 oba wyprodukowane z szablonu bodajże z wersji 1.8.6). 
Zmiany wprowadziłem z pliku: /etc/systemd/timesyncd.conf  
NTP=ntp.p.lodz.pl tempus1.gum.gov.pl tempus2.gum.gov.pl
i restart 
systemctl restart systemd-timesyncd.service

**Comment by bockpl** [comment]
No i opisałeś, co w zasadzie prezentujesz w pierwszym zdaniu zgłoszenia. Znaczy, że moje działanie było skuteczne:) 
Nadal nie wiem co masz na myśli pisząc "Proszę o wskazanie ścieżki do synchronizacji czasu". Masz na myśli podanie sposobu konfiguracji synchronizacji czasu w systemie stworzonym z obrazu?

**Comment by przemyslawtrzeciak** [comment]
Pisząc "Proszę o wskazanie ścieżki do synchronizacji czasu" mam na myśli wskazanie standardu którym powinienem się posłużyć w konfiguracji czasu, aby pozostać zgodnym z wypracowanym, ogólnym (zespołowym) rozwiązaniem.

**Comment by seweryn-S** [comment]
Czyli się dogadaliśmy. Standard będzie opracowany i wdrożony w poprawkach do wersji master. Mam nadzieję już niedługo.

**Comment by kedarnok** [comment]
Obraz zaktualizowany o wskazanie naszego ntp oraz została ustawiona nasza strefa czasowa.

**Comment by seweryn-S** [comment]
A w jakiej wersji ta poprawka?
